"""
embedding_classifier.py — Phase 4, step 3.

Trains three ML classifiers (Logistic Regression, Linear SVC, XGBoost) on
MiniLM sentence embeddings instead of TF-IDF, on the SAME leakage-safe
split and SAME body-text-only input (clean_text, no subject, no
sender_domain) as ablation_experiments.py Config C. This makes this a
fair apples-to-apples test of representation quality (TF-IDF vs.
transformer embeddings) rather than a comparison muddied by different
feature sets.

Requires email_embeddings.npy + email_embedding_ids.csv already
generated by embeddings.py.

Usage:
    python embedding_classifier.py generated_emails labels.csv
"""

import sys

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, f1_score, classification_report
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

from loader import load_emails
from cleaner import clean_dataframe
from split import group_aware_split, verify_no_leakage
from embeddings import load_embeddings


def align_embeddings_to_df(df: pd.DataFrame, embeddings: np.ndarray, ids: pd.Series):
    """Reorder embeddings to match df's row order (by filename), since
    train/test splitting happens on df, not directly on the embeddings array."""
    id_to_row = {fname: i for i, fname in enumerate(ids)}
    missing = [f for f in df["filename"] if f not in id_to_row]
    if missing:
        raise ValueError(
            f"{len(missing)} filenames in df have no embedding (e.g. {missing[:3]}) -- "
            f"regenerate embeddings.py against the current dataset first."
        )
    idx = [id_to_row[f] for f in df["filename"]]
    return embeddings[idx]


def train_and_evaluate(model, model_name, X_train, y_train, X_test, y_test, label_col="category"):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    macro_f1 = f1_score(y_test, y_pred, average="macro")

    print(f"\n{'=' * 60}")
    print(f"{model_name}")
    print(f"{'=' * 60}")
    print(f"Accuracy:  {acc:.3f}")
    print(f"Macro F1:  {macro_f1:.3f}")
    print(classification_report(y_test, y_pred, zero_division=0, digits=3))

    return {"model_name": model_name, "accuracy": acc, "macro_f1": macro_f1}


def main(emails_dir, labels_csv):
    df = load_emails(emails_dir, labels_csv)
    df = clean_dataframe(df)

    embeddings, ids = load_embeddings()
    embeddings = align_embeddings_to_df(df, embeddings, ids)
    df = df.reset_index(drop=True)  # ensure positional alignment with embeddings rows

    train_df, test_df = group_aware_split(df)
    verify_no_leakage(train_df, test_df)

    # Recover the same row positions in the (already-aligned) embeddings array
    # by filename, since group_aware_split returns new DataFrames with reset
    # indices -- we can't just slice `embeddings` by train_df's index directly.
    filename_to_emb_row = {f: i for i, f in enumerate(df["filename"])}
    train_emb_idx = [filename_to_emb_row[f] for f in train_df["filename"]]
    test_emb_idx = [filename_to_emb_row[f] for f in test_df["filename"]]

    X_train = embeddings[train_emb_idx]
    X_test = embeddings[test_emb_idx]
    y_train = train_df["category"].values
    y_test = test_df["category"].values

    print(f"\nX_train: {X_train.shape}, X_test: {X_test.shape}")
    print("(384-dim MiniLM embeddings of clean_text only -- no subject, no sender_domain, "
          "matching ablation Config C for a fair TF-IDF vs. embeddings comparison)")

    results = []

    lr = LogisticRegression(max_iter=1000, C=1.0)
    results.append(train_and_evaluate(lr, "Logistic Regression (MiniLM)", X_train, y_train, X_test, y_test))

    svc = LinearSVC(C=1.0, max_iter=5000)
    results.append(train_and_evaluate(svc, "Linear SVM (MiniLM)", X_train, y_train, X_test, y_test))

    # XGBoost needs integer-encoded labels, not strings
    le = LabelEncoder()
    y_train_enc = le.fit_transform(y_train)
    y_test_enc = le.transform(y_test)
    xgb = XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1,
                         eval_metric="mlogloss", n_jobs=-1, random_state=42)
    xgb.fit(X_train, y_train_enc)
    y_pred_enc = xgb.predict(X_test)
    y_pred = le.inverse_transform(y_pred_enc)
    acc = accuracy_score(y_test, y_pred)
    macro_f1 = f1_score(y_test, y_pred, average="macro")
    print(f"\n{'=' * 60}\nXGBoost (MiniLM)\n{'=' * 60}")
    print(f"Accuracy:  {acc:.3f}")
    print(f"Macro F1:  {macro_f1:.3f}")
    print(classification_report(y_test, y_pred, zero_division=0, digits=3))
    results.append({"model_name": "XGBoost (MiniLM)", "accuracy": acc, "macro_f1": macro_f1})

    print(f"\n{'=' * 60}")
    print("SUMMARY: MiniLM embedding classifier results")
    print(f"{'=' * 60}")
    for r in results:
        print(f"{r['model_name']:30s} accuracy={r['accuracy']:.3f}  macro_f1={r['macro_f1']:.3f}")
    print("\nNote: For TF-IDF comparison, run ablation.py Config C (body-only) to get")
    print("      current baseline numbers on your dataset.")

    return results


if __name__ == "__main__":
    emails_dir = sys.argv[1] if len(sys.argv) > 1 else "generated_emails"
    labels_csv = sys.argv[2] if len(sys.argv) > 2 else "labels.csv"
    main(emails_dir, labels_csv)