"""
Subject/body templates per category. Each entry is (subject_template,
body_template) using {placeholder} fields filled in by utils.fill_placeholders.
"""

TEMPLATES = {
    "College": [
        ("{course} Exam Schedule", "{course} exam is on {date}.\nPlease submit Assignment {num} before {date2}.\nVenue: Room {room}, Main Block."),
        ("Fee Payment Reminder", "Your semester fee of INR {amount} is due by {date}.\nPay online via the student portal to avoid late charges."),
        ("Guest Lecture Announcement", "A guest lecture on {topic} will be held on {date} at 4 PM in the Seminar Hall."),
        ("Result Declaration", "Results for the {course} mid-semester exam have been published. Check your grades: {url}"),
        ("Library Book Due", "The book '{book}' issued to you is due for return on {date}. Renew online to avoid a fine."),
        ("Timetable Change Notice", "The {course} lecture originally on {date} has been moved to {date2}, Room {room}."),
        ("Scholarship Application Open", "Applications for the merit scholarship are open until {date}. Award amount: INR {amount}. Apply here: {url}"),
        ("Hostel Fee Due", "Your hostel fee of INR {amount} is due by {date}. Pay via the accounts office."),
        ("Placement Drive Announcement", "{company} will be conducting a campus placement drive on {date} for the role of {role}."),
        ("Assignment Extension Granted", "The deadline for Assignment {num} in {course} has been extended to {date2}."),
        ("Convocation Notice", "Convocation ceremony will be held on {date}. Collect your gown by {date2}."),
        ("Internal Marks Query Window", "The window to raise queries about your {course} internal marks closes on {date}."),
    ],
    "Finance": [
        ("Credit Card Statement Generated", "Your credit card statement for the period ending {date} is ready.\nTotal due: INR {amount}.\nMinimum due: INR {amount2}."),
        ("Transaction Alert", "INR {amount} was debited from your account ending 4821 on {date} at {company}."),
        ("Investment Update", "Your mutual fund portfolio has grown by {pct}% this quarter. View details: {url}"),
        ("Loan EMI Reminder", "Your EMI of INR {amount} for Personal Loan #{num} is due on {date}."),
        ("Tax Filing Reminder", "Income tax filing deadline is approaching. Please file your returns before {date} to avoid penalties."),
        ("Fixed Deposit Matured", "Your fixed deposit of INR {amount} matured on {date}. Choose to renew or withdraw."),
        ("Salary Credited", "INR {amount} has been credited to your account on {date} as salary from {company}."),
        ("Insurance Premium Due", "Your policy premium of INR {amount} is due on {date}. Pay now to keep your policy active."),
        ("Low Balance Alert", "Your account balance is below INR {amount}. Add funds here: {url}"),
        ("New Card Offer", "You are pre-approved for a credit limit increase to INR {amount}. Accept before {date}: {url}"),
        ("Autopay Setup Confirmation", "Autopay for your {company} bill has been set up, starting {date}."),
        ("Quarterly Portfolio Report", "Your quarterly investment report is ready. Net change: {pct}% as of {date}."),
    ],
    "Shopping": [
        ("{company} Mega Sale", "Up to 60% OFF on electronics and fashion.\nSale ends {date}. Use code SAVE{num} at checkout."),
        ("Order Shipped", "Your order #{num} from {company} has shipped and will arrive by {date}. Track it: {url}"),
        ("Price Drop Alert", "An item in your wishlist just dropped to INR {amount}. Grab it before it's gone!"),
        ("Order Delivered", "Your package from {company} was delivered on {date}. Rate your experience."),
        ("Cart Reminder", "You left {num} item(s) in your cart. Complete your purchase and get free shipping."),
        ("Flash Sale - 4 Hours Only", "Flash sale live now at {company}! Extra {pct}% off, ends {date}."),
        ("Return Confirmation", "Your return for order #{num} has been received. Refund of INR {amount} will be processed by {date}. Details: {url}"),
        ("New Arrivals in Your Category", "New arrivals from {company} matching your interests are now live: {url}"),
        ("Order Delayed", "Your order #{num} from {company} is delayed and will now arrive by {date2} instead of {date}. Track: {url}"),
        ("Wishlist Reminder", "Items in your wishlist are still available. Buy now before prices go up on {date}."),
        ("Refer a Friend, Get INR {amount}", "Invite a friend to {company} and both of you get INR {amount} credit. Share your link: {url}"),
        ("Subscription Renewal", "Your {company} membership renews on {date} for INR {amount}."),
    ],
    "Travel": [
        ("Flight Booking Confirmation", "Your flight to {city} on {date} is confirmed.\nBooking reference: {ref}.\nDeparture: 10:30 AM."),
        ("Hotel Reservation", "Your stay at {city} Grand Hotel from {date} to {date2} is confirmed. Booking ID: {ref}."),
        ("Visa Application Update", "Your visa application for {city} has moved to 'Under Review'. Expected decision by {date}."),
        ("Travel Insurance Policy Issued", "Your travel insurance policy #{ref} for the {city} trip is now active."),
        ("Itinerary Change", "Your connecting flight to {city} has been rescheduled to {date}. Please check your booking."),
        ("Check-in Now Open", "Online check-in for your flight to {city} on {date} is now open. Check in here: {url}"),
        ("Car Rental Confirmation", "Your car rental in {city} from {date} to {date2} is confirmed. Booking ID: {ref}. Manage booking: {url}"),
        ("Trip Reminder", "Your trip to {city} starts on {date}. Don't forget to check the weather and pack accordingly."),
        ("Boarding Pass Attached", "Your boarding pass for the {date} flight to {city} is attached to this email."),
        ("Refund Processed", "Your refund of INR {amount} for the cancelled {city} trip has been processed. Details: {url}"),
        ("Loyalty Points Credited", "You've earned {num}00 loyalty points for your recent trip to {city}."),
        ("Travel Advisory", "Please note a travel advisory is in effect for {city} as of {date}. Read the advisory: {url}"),
    ],
    "Spam": [
        ("You've Won a Prize!", "Congratulations! You have been selected to win INR {amount}. Click here to claim now before it expires: {url}"),
        ("Urgent: Verify Your Account", "Your account will be suspended in 24 hours. Verify your details immediately: {url}"),
        ("Free iPhone Giveaway", "You are our lucky visitor! Claim your free iPhone {num} today. Limited slots available."),
        ("Investment Opportunity", "Double your money in 7 days! Join now, limited seats, guaranteed returns."),
        ("Lottery Winner Notification", "Your email was randomly selected in the International Lottery. Prize: ${amount}. Reply to claim."),
        ("Your Package is Held at Customs", "Pay a small fee of INR {amount} to release your package. Click here to proceed: {url}"),
        ("Work From Home, Earn INR {amount}/day", "No experience needed! Earn INR {amount} daily working just 2 hours from home."),
        ("Your Account Password Expired", "Click here immediately to reset your password or lose access permanently: {url}"),
        ("Congratulations, Gift Card Winner", "You've won a INR {amount} gift card from {company}. Redeem within 24 hours: {url}"),
        ("Final Notice: Unusual Login Detected", "We detected a login from {city}. Confirm it was you or your account will be locked: {url}"),
        ("Exclusive Crypto Airdrop", "Claim your free crypto airdrop worth ${amount} before {date}. Claim here: {url}"),
        ("Your Subscription is Expiring, Act Now", "Renew now to avoid losing access. Special price: INR {amount}, today only: {url}"),
    ],
    "Social": [
        ("{name} tagged you in a photo", "{name} tagged you in a photo from '{event}'. Check it out and leave a comment!"),
        ("New Follower", "{name} started following you. See their profile: {url}"),
        ("Event Invitation", "You're invited to {event} on {date}. RSVP now to let the host know you're coming."),
        ("Birthday Reminder", "It's {name}'s birthday on {date}! Send them a message to make their day."),
        ("New Message", "You have a new message from {name}: \"Hey, are we still meeting on {date}?\""),
        ("{name} commented on your post", "{name} commented: \"This is amazing, congrats!\" on your recent post."),
        ("Group Invitation", "{name} invited you to join the group '{event}'."),
        ("Memory From {date2}", "You have a memory from {date2}. See what you posted that day."),
        ("{name} liked your photo", "{name} and {num} others liked your recent photo."),
        ("Weekly Digest", "Here's what you missed this week from {name} and {num} others."),
        ("Poke from {name}", "{name} poked you. Poke them back!"),
        ("Suggested Connection", "You may know {name}, who works at {company}. Connect now: {url}"),
    ],
    "Job": [
        ("Interview Invitation - {company}", "We would like to invite you for an interview for the {role} position on {date} at 3 PM via Google Meet."),
        ("Application Received", "Thank you for applying to the {role} role at {company}. Our team will review your application shortly."),
        ("Offer Letter", "Congratulations! {company} is pleased to offer you the position of {role}. Please respond by {date}."),
        ("New Job Match", "A new job matching your profile was posted: {role} at {company}, {city}. Apply now: {url}"),
        ("Someone starred your repository", "{name} starred your repository on GitHub. Keep up the great work!"),
        ("Application Status Update", "Your application for {role} at {company} has moved to the next round. Details: {url}"),
        ("Take-Home Assignment", "Please complete the take-home assignment for the {role} role at {company} by {date}. Assignment link: {url}"),
        ("Reference Check Request", "{company} would like to contact your references for the {role} position. Please confirm by {date}."),
        ("Rejection Notice", "Thank you for interviewing for {role} at {company}. We've decided to move forward with other candidates."),
        ("Onboarding Details", "Welcome to {company}! Your onboarding for the {role} role begins on {date}."),
        ("Recruiter Outreach", "Hi, I'm a recruiter at {company}. We have an exciting {role} opening in {city} - interested? Job link: {url}"),
        ("Salary Negotiation Follow-up", "Following up on our conversation regarding the {role} offer. Let's finalize by {date}."),
    ],
    "Government": [
        ("Passport Renewal Reminder", "Your passport is due for renewal within 6 months. Schedule an appointment before {date}."),
        ("Voter ID Update", "Your voter registration has been successfully updated with your new address effective {date}."),
        ("Property Tax Notice", "Your property tax of INR {amount} for this fiscal year is due by {date}. Pay online to avoid penalty."),
        ("Passport Application Status", "Your passport application #{ref} status has been updated to 'Ready for Dispatch'."),
        ("Public Notice: Water Supply", "Water supply will be interrupted in your area on {date} from 10 AM to 4 PM for maintenance work."),
        ("Jury Duty Summons", "You have been summoned for jury duty on {date}. Report to the courthouse by 9 AM."),
        ("Driving License Renewal", "Your driving license expires on {date}. Renew online: {url}"),
        ("Census Participation Reminder", "Please complete the national census survey before {date}."),
        ("Utility Bill Subsidy Update", "You are eligible for a subsidy of INR {amount} on your utility bill this quarter."),
        ("Municipal Election Notice", "Municipal elections will be held on {date}. Locate your polling booth: {url}"),
        ("Social Security Update", "Your social security details have been updated as of {date}."),
        ("Building Permit Approved", "Your building permit application #{ref} has been approved as of {date}."),
    ],
}

THREAD_PREFIXES = ["Re: ", "Fwd: "]

REPLY_SNIPPETS = [
    "Thanks for the update, noted.",
    "Got it, will follow up soon.",
    "Please see my response below.",
    "Forwarding this for your reference.",
    "Just circling back on this - any update?",
    "Confirmed, thank you.",
]
